name: Feature Request
description: Suggest a new feature or enhancement
title: '[Feature] '
labels: ['enhancement']

body:
  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package or component is this for?
      options:
        - '@tasker-ai/cli'
        - '@tasker-ai/sdk'
        - '@tasker-ai/skills'
        - Web App
        - New Package
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the feature you'd like to see
      placeholder: What feature would you like?
    validations:
      required: true

  - type: textarea
    id: usecase
    attributes:
      label: Use Case
      description: Why do you need this feature? What problem does it solve?
      placeholder: Explain the use case and why this is needed...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this feature work?
      placeholder: Describe your proposed solution...

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches did you consider?
      placeholder: What alternatives exist?
